name: Update Release Draft

on:
  push:
    branches:
      - master

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Release draft
        id: release_draft
        uses: release-drafter/release-drafter@v5.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}